### PR TITLE
start implementing pepecoin

### PR DESCRIPTION
**Pull request by PepeEnthusiast**
Hello! I find your project very interesting. Good job on the development!

In this pull request I started to implement the pepecoin blockchain in the 'node' package.

I also added the blockchain parameters in nakamotojs/ts_src/networks.ts and recompiled the package.

The pepecoin-core docker image I published is multi-architecture, almost identical to the litecoin-core docker image.

There is some changes that will need to be done in the compiled code, that is outside of my control so someone from the team will need to finish the implementation. Hopefully the implementation on your side should be relatively easy.

As I am not familiar with the core of this project there might be some things I missed, if so please let me know and I will try my best to correct it. Obviously I did not make any changes to the other packages as I figured we should get the node package working first.

Thank you :)

### CODE REVIEW

**Comment by ClemensLey** [comment]
This is great work, thank you very much. As discussed we have to make some changes to the core library to enable adding other chains. If that's ok we will directly push to this branch to ensure you both become a contributors when the branch gets merged. We're excited about adding support for Pepecoin!

**Comment by ltardivo** [comment]
Great contribution! Could you add the Dockerfile to this PR, so that we can build the docker image for the node of pepecoin and upload it to our docker [hub account](https://hub.docker.com/u/bcdb), like for the other coins? Thank you!

**Comment by PepeEnthusiast** [comment]
The Dockerfile can be found here
https://github.com/PepeEnthusiast/docker-pepecoin-core/tree/master/1.0.1

**Comment by ltardivo** [comment]
We have published the version 0.20.1-beta.0 with experimental support for pepecoin. Thanks @PepeEnthusiast and @Unknown-Kush for your contributions!. If you have any issues or discover any bugs, please let us know and/or create another PR. Thank you!

**Pull request merged**
